export const quickAccessIconOptions = [
  { value: "ClipboardList", label: "Admissions" },
  { value: "GraduationCap", label: "Graduation Cap" },
  { value: "HeartHandshake", label: "Student Support" },
  { value: "Bell", label: "Notice Bell" },
  { value: "FileText", label: "Document" },
  { value: "BookOpen", label: "Book" },
  { value: "CalendarDays", label: "Calendar" },
  { value: "Users", label: "People" },
  { value: "Images", label: "Gallery" },
  { value: "Landmark", label: "Campus" },
  { value: "Cpu", label: "Technology" },
  { value: "Briefcase", label: "Business" },
  { value: "Microscope", label: "Science" },
  { value: "Scale", label: "Law / Policy" },
  { value: "Stethoscope", label: "Health" },
  { value: "Sprout", label: "Agriculture" },
];
