export type ImageAsset = {
  url: string;
  secureUrl?: string;
  publicId?: string;
  width?: number;
  height?: number;
  format?: string;
  altText?: string;
};

export type EditableListItem = {
  icon?: string;
  title: string;
  body: string;
};

export type IconTitleItem = {
  icon?: string;
  title: string;
  body?: string;
};

export type SiteSettings = {
  universityName: string;
  tagline: string;
  logo?: ImageAsset;
  favicon?: ImageAsset;
  address: string;
  phone: string;
  email: string;
  facebook?: string;
  youtube?: string;
  linkedin?: string;
  seoTitle: string;
  seoDescription: string;
};

export type HomeSlide = {
  eyebrow: string;
  title: string;
  subtitle: string;
  buttonLabel: string;
  buttonHref: string;
  image?: ImageAsset;
};

export type HomeFeatureCard = {
  title: string;
  body: string;
  href: string;
};

export type HomeQuickAccessCard = {
  icon: string;
  title: string;
  subtitle: string;
  href: string;
};

export type HomeAcademicCard = {
  icon: string;
  title: string;
};

export type HomeNotice = {
  title: string;
  body: string;
  category: string;
  date: string;
};

export type HomePage = {
  slides: HomeSlide[];
  introEyebrow?: string;
  introTitle: string;
  introBody: string;
  introHighlight?: string;
  introImage?: ImageAsset;
  introImageEyebrow?: string;
  introImageCaption?: string;
  statProgramsValue?: string;
  statProgramsLabel?: string;
  statProgramsDetail?: string;
  statUpdatesValue?: string;
  statUpdatesLabel?: string;
  statUpdatesDetail?: string;
  featureTitle: string;
  featureBody: string;
  featureCards: HomeFeatureCard[];
  quickAccessCards?: HomeQuickAccessCard[];
  academicCards?: HomeAcademicCard[];
  academicTitle: string;
  academicBody: string;
  academicEyebrow?: string;
  academicButtonLabel?: string;
  academicButtonHref?: string;
  noticeTitle: string;
  noticeEyebrow?: string;
  noticeButtonLabel?: string;
  noticeButtonHref?: string;
  newsTitle: string;
  newsBody: string;
  newsEyebrow?: string;
  newsButtonLabel?: string;
  newsButtonHref?: string;
  newsPageEyebrow?: string;
  newsPageTitle?: string;
  newsPageBody?: string;
  selectedMainNewsSlug?: string;
  selectedNewsSlugs?: string[];
  selectedNoticeSlugs?: string[];
  selectedEventSlugs?: string[];
  galleryTitle: string;
  galleryBody: string;
  galleryEyebrow?: string;
  galleryQuote?: string;
  galleryPrimaryLabel?: string;
  galleryPrimaryHref?: string;
  gallerySecondaryLabel?: string;
  gallerySecondaryHref?: string;
  galleryPageEyebrow?: string;
  galleryPageTitle?: string;
  galleryPageBody?: string;
  galleryMosaicImages?: ImageAsset[];
  selectedGallerySlugs?: string[];
  notices: HomeNotice[];
  ctaEyebrow?: string;
  ctaTitle: string;
  ctaBody: string;
  ctaButtonLabel: string;
  ctaHref: string;
  ctaSecondaryLabel?: string;
  ctaSecondaryHref?: string;
  ctaTrustBadges?: string[];
  ctaBackgroundImage?: ImageAsset;
};

export type AboutPage = {
  aboutHeroEyebrow?: string;
  aboutHeroTitle?: string;
  aboutHeroBody?: string;
  aboutIntroEyebrow?: string;
  aboutTitle: string;
  aboutBody: string;
  aboutIntroExtra?: string;
  aboutImage?: ImageAsset;
  aboutImageBadgeEyebrow?: string;
  aboutImageBadgeText?: string;
  aboutPrimaryButtonLabel?: string;
  aboutPrimaryButtonHref?: string;
  aboutSecondaryButtonLabel?: string;
  aboutSecondaryButtonHref?: string;
  aboutPillarsEyebrow?: string;
  aboutPillarsTitle?: string;
  aboutPillars?: EditableListItem[];
  aboutStatsEyebrow?: string;
  aboutStatsTitle?: string;
  aboutStats?: EditableListItem[];
  aboutJourneyEyebrow?: string;
  aboutJourneyTitle?: string;
  aboutJourneyBody?: string;
  aboutJourneyItems?: EditableListItem[];
  aboutWhyEyebrow?: string;
  aboutWhyTitle?: string;
  aboutWhyBody?: string;
  aboutWhyItems?: IconTitleItem[];
  aboutCampusEyebrow?: string;
  aboutCampusTitle?: string;
  aboutCampusBody?: string;
  aboutCampusFeatures?: string[];
  aboutCampusMainImage?: ImageAsset;
  aboutCampusTopImage?: ImageAsset;
  aboutCampusBottomImage?: ImageAsset;
  aboutLeadershipEyebrow?: string;
  aboutLeadershipTitle?: string;
  aboutLeadershipBody?: string;
  aboutLeadershipPrimaryLabel?: string;
  aboutLeadershipPrimaryHref?: string;
  aboutLeadershipSecondaryLabel?: string;
  aboutLeadershipSecondaryHref?: string;
  aboutCtaEyebrow?: string;
  aboutCtaTitle?: string;
  aboutCtaBody?: string;
  aboutCtaPrimaryLabel?: string;
  aboutCtaPrimaryHref?: string;
  aboutCtaSecondaryLabel?: string;
  aboutCtaSecondaryHref?: string;
  aboutCtaImage?: ImageAsset;
  missionIntroTitle?: string;
  missionIntroBody?: string;
  missionHeroEyebrow?: string;
  missionHeroTitle?: string;
  missionHeroBody?: string;
  missionHeroImage?: ImageAsset;
  missionIntroEyebrow?: string;
  missionTitle: string;
  missionBody: string;
  missionPoints?: EditableListItem[];
  visionTitle: string;
  visionBody: string;
  missionVisionCardTitle?: string;
  missionCoreValuesEyebrow?: string;
  missionCoreValuesTitle?: string;
  coreValues?: EditableListItem[];
  missionStrategicEyebrow?: string;
  missionStrategicTitle?: string;
  strategicFocus?: EditableListItem[];
  missionQuote?: string;
  missionQuoteSource?: string;
  missionCtaEyebrow?: string;
  missionCtaTitle?: string;
  missionCtaBody?: string;
  missionCtaPrimaryLabel?: string;
  missionCtaPrimaryHref?: string;
  missionCtaSecondaryLabel?: string;
  missionCtaSecondaryHref?: string;
  chairmanName: string;
  chairmanRole: string;
  chairmanHeroEyebrow?: string;
  chairmanHeroTitle?: string;
  chairmanHeroBody?: string;
  chairmanHeroImage?: ImageAsset;
  chairmanProfileEyebrow?: string;
  chairmanQuote?: string;
  chairmanIntro?: string;
  chairmanMessageEyebrow?: string;
  chairmanMessage: string;
  chairmanPhoto?: ImageAsset;
  chairmanCommitmentsEyebrow?: string;
  chairmanCommitmentsTitle?: string;
  chairmanCommitments?: EditableListItem[];
  chairmanPrioritiesEyebrow?: string;
  chairmanPrioritiesTitle?: string;
  chairmanPrioritiesBody?: string;
  chairmanPriorities?: EditableListItem[];
  chairmanClosingNote?: string;
  chairmanRelatedEyebrow?: string;
  chairmanRelatedTitle?: string;
  chairmanRelatedLinks?: EditableListItem[];
  committeeSubtitle?: string;
  committeeHeroEyebrow?: string;
  committeeHeroTitle?: string;
  committeeHeroImage?: ImageAsset;
  committeeIntroEyebrow?: string;
  committeeIntroTitle?: string;
  committeeIntro?: string;
  committeeResponsibilitiesEyebrow?: string;
  committeeResponsibilitiesTitle?: string;
  committeeResponsibilities?: EditableListItem[];
  committeeLeadershipEyebrow?: string;
  committeeLeadershipTitle?: string;
  committeeLeadershipBody?: string;
  committeeMeetingTitle?: string;
  committeeMeetingBody?: string;
  committeeMeetingFrequency?: string;
  committeeMeetingOffice?: string;
  committeeMeetingEmail?: string;
  committeeDocumentsTitle?: string;
  committeeDocuments?: EditableListItem[];
  committeeCtaEyebrow?: string;
  committeeCtaTitle?: string;
  committeeCtaBody?: string;
  committeeCtaButtonLabel?: string;
  committeeCtaButtonHref?: string;
};

export type AcademicPage = {
  title: string;
  overview: string;
  heroEyebrow?: string;
  heroImage?: ImageAsset;
  programCardBody?: string;
  programs: string[];
  admissionTitle: string;
  admissionBody: string;
  downloads: { label: string; href: string }[];
};

export type ContactPage = {
  title: string;
  intro: string;
  heroLabel?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: ImageAsset;
  addressLabel?: string;
  address: string;
  addressNote?: string;
  phoneLabel?: string;
  phone: string;
  phoneNote?: string;
  emailLabel?: string;
  email: string;
  emailNote?: string;
  officeHoursLabel?: string;
  officeHours: string;
  officeHoursNote?: string;
  formEyebrow?: string;
  formTitle?: string;
  formBody?: string;
  mapEyebrow?: string;
  mapTitle?: string;
  mapEmbedUrl?: string;
  mapDirectionUrl?: string;
  mapDirectionLabel?: string;
  mapNote?: string;
  departmentEyebrow?: string;
  departmentTitle?: string;
  departmentBody?: string;
  departments?: DepartmentContact[];
  urgentTitle?: string;
  urgentBody?: string;
  urgentButtonLabel?: string;
};

export type DepartmentContact = {
  title: string;
  body: string;
  email: string;
  phone: string;
};

export type CommitteeMember = {
  _id?: string;
  name: string;
  role: string;
  committeeRole?: string;
  department?: string;
  email?: string;
  officePhone?: string;
  profileUrl?: string;
  bio?: string;
  order: number;
  published: boolean;
  photo?: ImageAsset;
};

export type NewsEvent = {
  _id?: string;
  title: string;
  slug: string;
  date: string;
  category: string;
  department?: string;
  excerpt: string;
  body: string;
  published: boolean;
  featured?: boolean;
  coverImage?: ImageAsset;
  eventDate?: string;
  eventTime?: string;
  eventLocation?: string;
  organizer?: string;
  eventStatus?: "Upcoming" | "Ongoing" | "Completed";
  registrationLink?: string;
  pdfUrl?: string;
  tags?: string[];
  seoTitle?: string;
  seoDescription?: string;
};

export type GalleryItem = {
  _id?: string;
  title: string;
  slug?: string;
  category: string;
  department?: string;
  year?: string;
  eventDate?: string;
  description?: string;
  order: number;
  published: boolean;
  featured?: boolean;
  image?: ImageAsset;
  coverImage?: ImageAsset;
  images?: GalleryImage[];
  mediaType?: "Photos" | "Videos";
  videoUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type GalleryImage = ImageAsset & {
  title?: string;
  caption?: string;
  order?: number;
  uploadedAt?: string;
};

export type ContactMessage = {
  name: string;
  email: string;
  phone?: string;
  inquiryType?: string;
  subject: string;
  message: string;
  createdAt: string;
  read: boolean;
};
